### ISSUE TITLE
product planning

### ISSUE THREAD

**Issue by gnomex** [andersonfernandes/finances-api#35]
Hey guys, do you have a product planning, including feature you would like to have?

if you don't have, I was about to start a **Money Management System** (like what you've been doing) project, who knows, maybe we can merge the ideas.

Let me know if I can help and how. Thanks

**Comment by andersonfernandes** [comment]
Hi @gnomex, we can talk about this merge of ideas.
If you use Telegram, send me some message there, my user is @fernandesanderson. If dont send me an e-mail at fernandesanderson14@gmail.com with some contact info.
