### ISSUE TITLE
Atualizar colunas na tabela accounts

### ISSUE THREAD

**Issue by andersonfernandes** [andersonfernandes/finances-api#84]
Removeremos algumas colunas ta tabela **`accounts`**, tais colunas serão realocadas para uma nova tabela no futuro.

As colunas que devem ser removidas são:

- [x] `initial_amount`
- [x] `account_type`, removendo o enum também
- [x] `financial_institution_id`, removendo o `belongs_to` também

Ao finalizar a remoção, certifique-se que os endpoints, documentação e testes que usavam essas colunas sejam atualizados.

**Comment by likannp** [comment]
Bom dia @andersonfernandes, tudo bem? Posso fazer?
