### ISSUE TITLE
Atualizar colunas da tabela credit_cards

### ISSUE THREAD

**Issue by andersonfernandes** [andersonfernandes/finances-api#86]
Removeremos algumas colunas da tabela **`credit_cards`** e adicionaremos algumas novas.

- [ ] Remover a coluna `closing_day`
- [ ] Remover a relação `account_id`, removendo o `belongs_to` também
- [ ] A coluna `due_day` deve ser renomeada para `billing_day`
- [ ] Adicionar a relação com a tabela de `users` através da foreign key `user_id`.

Ao finalizar as alterações, certifique-se que os endpoints, documentação e testes sejam atualizados.

Segue o diagrama da reestruturação do banco:
 
![Tables-New Tables](https://user-images.githubusercontent.com/8173530/195607541-a2ebc71c-dcd8-4b97-9100-d2faf77f3340.png)

**Comment by likannp** [comment]
Boa noite @andersonfernandes, posso fazer?
